AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  url-shortner

Parameters:
  Stage:
    Type: String
    Default: 'dev'

Globals:
  Function:
    Timeout: 10

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 
        Ref: Stage
  
  GenerateShortUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/generate_url/
      Handler: app.index
      Runtime: python3.8
      Events:
        GenerateShourtUrlApi:
          Type: Api
          Properties:
            Path: /generate
            Method: post
            RestApiId:
              Ref: ApiGatewayApi

Outputs:
  ApiGatewayBaseUrl:
    Description: "API Gateway base url"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
